# Generated by Django 3.1 on 2022-03-07 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('location', models.CharField(max_length=50, verbose_name='場所')),
                ('text', models.TextField(verbose_name='内容')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('birthday', models.DateField(verbose_name='誕生日')),
                ('memo', models.TextField(verbose_name='一言')),
            ],
        ),
    ]
