# Generated by Django 3.1 on 2022-03-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20220307_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member',
            field=models.ManyToManyField(to='info.Member', verbose_name='担当者'),
        ),
    ]
