# Generated by Django 3.1 on 2022-04-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_event_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
