# Generated by Django 3.1 on 2022-04-07 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_member_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='締め切り日'),
        ),
    ]
