# Generated by Django 3.1 on 2022-04-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_event_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
